server:
  port: 8090
spring:
  sql:
    init:
      mode: always
  datasource:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  kafka:
    bootstrap-servers: kafka:29092
    group-id: employee
    topic:
      employee:
        create: createEmployee
        change-state: changeState
        reply: replyEmployee